// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface State {
    "version": number;
    "revision": number;
    "selected": string;
    "themes": Theme[] | null;
}

export interface Theme {
    "id": string;
    "name": string;
    "base": string;
    "colors": { [_ in string]?: string } | null;
    "grain": boolean;
    "readOnly": boolean;
}
