// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filtereval$0 from "./internal/filtereval/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prices$0 from "./internal/prices/models.js";

export interface BrowserLinkStatus {
    "state": string;

    /**
     * Connected reports a stored session (the overlay searches signed in).
     */
    "connected": boolean;
    "connectedAt": number;

    /**
     * URL is the link to open by hand in another browser (the code is valid
     * until the request ends).
     */
    "url"?: string;
    "error"?: string;

    /**
     * Rules is GGG's rate-limit policy on the last search ("Account,Ip" when
     * it counted the search as signed in, "Ip" when not; "" before any).
     */
    "rules"?: string;

    /**
     * ExtensionOutdated is set when the extension that answered is older
     * than the one this app carries: its folder has been refreshed, and the
     * browser needs "Reload" on its extensions page to pick it up.
     */
    "extensionOutdated"?: boolean;
}

/**
 * ChromiumBrowser is an installed Chromium-based browser the extension can
 * be loaded into (unpacked, from its extensions page in developer mode).
 */
export interface ChromiumBrowser {
    "id": string;
    "name": string;

    /**
     * Page is the browser's own extensions page ("edge://extensions").
     */
    "page": string;
    "default": boolean;
}

/**
 * CraftImport is the copied item the craft page turns into a draft.
 */
export interface CraftImport {
    "raw": string;
    "class": string;
    "rarity": string;
    "baseType": string;
    "itemLevel": number;
}

/**
 * CraftPrices exposes only public currency quotes. Past operations keep their
 * own price snapshot in the craft ledger when this list is refreshed.
 */
export interface CraftPrices {
    "league": string;
    "generated_at": string;
    "currency": prices$0.CurrencyPrice[] | null;
}

/**
 * FilterExplanation is what the written filter does with an item and why.
 */
export interface FilterExplanation {
    /**
     * Final is the block that decides the item (the first certain match
     * without Continue); nil when no rule matches and the game shows it.
     */
    "final"?: filtereval$0.Match | null;

    /**
     * Maybe are blocks above Final that would decide instead if their
     * unknown conditions hold, nearest first.
     */
    "maybe"?: filtereval$0.Match[] | null;

    /**
     * Decorations are Continue blocks that matched above Final and lent it
     * their looks (NeverSink's "ilvl 82" or "corrupted" frames).
     */
    "decorations"?: filtereval$0.Match[] | null;
    "verdict": filtereval$0.Verdict;

    /**
     * FilterPath and WrittenAt describe the file the answer comes from; the
     * game may still use an older copy until the filter is reloaded.
     */
    "filterPath": string;
    "writtenAt": string;

    /**
     * AreaLevel and Area are the last area of this game session (hideouts
     * and towns skipped), used for NeverSink's AreaLevel rules; 0 = unknown.
     */
    "areaLevel": number;
    "area": string;
}

/**
 * LanguageOption is one entry of the language picker.
 */
export interface LanguageOption {
    "id": string;
    "label": string;

    /**
     * Auto marks the entry that follows the Windows display language. Label is
     * the language that choice currently resolves to, Resolved its code.
     */
    "auto": boolean;
    "resolved"?: string;
}

/**
 * Meta is static information for the UI.
 */
export interface Meta {
    "version": string;
    "dataDir": string;
    "gameDir": string;

    /**
     * writing somewhere other than the game folder
     */
    "testMode": boolean;

    /**
     * MaxItemGroups is how many of their own groups a user may keep.
     */
    "maxItemGroups": number;
}

/**
 * StartupStatus is read from Windows rather than saved in the filter config.
 */
export interface StartupStatus {
    "enabled": boolean;
    "canChange": boolean;
    "state": string;
}

/**
 * StyleOptions are the choices offered in the custom style editor.
 */
export interface StyleOptions {
    "colours": string[] | null;
    "shapes": string[] | null;

    /**
     * group -> NeverSink style tag
     */
    "preset": { [_ in string]?: string } | null;

    /**
     * Sounds are the PlayAlertSound ids, so the panel and the filter writer
     * cannot drift apart about what the game accepts.
     */
    "sounds": string[] | null;
}
