// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the API the panel calls. Its methods are exposed to the
 * frontend through generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appupdate$0 from "../appupdate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filter$0 from "../filter/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as insights$0 from "../insights/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as overlay$0 from "../overlay/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as publicprofile$0 from "../publicprofile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trade$0 from "../trade/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uitheme$0 from "../uitheme/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddExotic adds an entry to the Exotic group and rewrites the filter.
 */
export function AddExotic(entry: filter$0.ExoticEntry): $CancellablePromise<$models.HideResult> {
    return $Call.ByID(1427261726, entry);
}

/**
 * AddSound copies a sound the user picks into the filter folder, which is the
 * only place the game reads CustomAlertSound files from. It returns the name
 * the file ended up with, or "" if the dialog was cancelled.
 */
export function AddSound(): $CancellablePromise<string> {
    return $Call.ByID(2101217483);
}

/**
 * BrowserLinkState is polled by Settings while a connection is in progress.
 */
export function BrowserLinkState(): $CancellablePromise<$models.BrowserLinkStatus> {
    return $Call.ByID(2817671892);
}

/**
 * CancelBrowserConnect stops waiting for the extension.
 */
export function CancelBrowserConnect(): $CancellablePromise<$models.BrowserLinkStatus> {
    return $Call.ByID(1557833781);
}

/**
 * CheckForAppUpdate checks GitHub Releases now, regardless of the daily timer.
 */
export function CheckForAppUpdate(): $CancellablePromise<appupdate$0.State> {
    return $Call.ByID(2181989680);
}

/**
 * ChromiumBrowsers lists the Chromium browsers found through Windows' "App
 * Paths" registration, the default browser marked.
 */
export function ChromiumBrowsers(): $CancellablePromise<$models.ChromiumBrowser[] | null> {
    return $Call.ByID(342838824);
}

export function ClearLiveResults(id: string): $CancellablePromise<trade$0.LiveState[] | null> {
    return $Call.ByID(2538878790, id);
}

/**
 * CommunityLinks lists the community buttons that have an address, in order.
 */
export function CommunityLinks(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2447826607);
}

/**
 * ConnectBrowser starts (or restarts) a connection: a new code, the local
 * listener, and optionally the default browser on pathofexile.com.
 */
export function ConnectBrowser(openBrowser: boolean): $CancellablePromise<$models.BrowserLinkStatus> {
    return $Call.ByID(1377611955, openBrowser);
}

/**
 * CraftLibrary returns the saved crafts as JSON text ("[]" when there are none).
 */
export function CraftLibrary(): $CancellablePromise<string> {
    return $Call.ByID(3888147020);
}

export function CreateSearchFolder(name: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(1348054129, name);
}

export function CreateUITheme(sourceID: string, name: string): $CancellablePromise<uitheme$0.State> {
    return $Call.ByID(2260403068, sourceID, name);
}

/**
 * DefaultChatCommands are the game command shortcuts a new install starts
 * with, for the settings page's "restore defaults".
 */
export function DefaultChatCommands(): $CancellablePromise<overlay$0.ChatCommand[] | null> {
    return $Call.ByID(3166849358);
}

export function DeleteOverlaySearch(id: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(768745922, id);
}

/**
 * DeleteProfile removes a profile and switches away from it when it was
 * active. A followed profile stops being followed; a published one is taken
 * off the server (its followers keep their last copy).
 */
export function DeleteProfile(name: string): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(2240805447, name);
}

/**
 * DeleteSearchFolder removes a folder and moves its searches to the top level.
 */
export function DeleteSearchFolder(id: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(3261759658, id);
}

export function DeleteUITheme(id: string): $CancellablePromise<uitheme$0.State> {
    return $Call.ByID(2475084489, id);
}

/**
 * DisconnectBrowser forgets the stored session; searches go out anonymous.
 */
export function DisconnectBrowser(): $CancellablePromise<$models.BrowserLinkStatus> {
    return $Call.ByID(1127413969);
}

/**
 * DownloadAppUpdate downloads and verifies the release executable.
 */
export function DownloadAppUpdate(): $CancellablePromise<appupdate$0.State> {
    return $Call.ByID(2346477993);
}

/**
 * EvaluateOverlay reuses identical successful searches for ten minutes unless
 * refresh is true. In-flight requests are shared as well, so opening Market
 * while the compact overlay is evaluating cannot consume a second GGG search.
 */
export function EvaluateOverlay($in: trade$0.EvaluateRequest, refresh: boolean): $CancellablePromise<trade$0.Evaluation> {
    return $Call.ByID(3391542250, $in, refresh);
}

/**
 * ExoticCandidates lists the copied item's base and named explicit
 * modifiers (as the advanced copy writes them) for Alt+E's "add to Exotic".
 * Only Normal, Magic and Rare gear qualifies.
 */
export function ExoticCandidates(raw: string): $CancellablePromise<$models.ExoticCandidate[] | null> {
    return $Call.ByID(1277147297, raw);
}

/**
 * ExoticModOptions lists the explicit modifiers items of the class can roll,
 * with their tiers (best first) and the names they share with other
 * modifiers of the class.
 */
export function ExoticModOptions($class: string): $CancellablePromise<$models.ExoticModOption[] | null> {
    return $Call.ByID(1960723781, $class);
}

/**
 * ExoticNeverSink lists NeverSink's exotic entries (bases and modifier
 * names) from the base filter on disk; the panel lays the player's changes
 * (Config.Exotic) over them.
 */
export function ExoticNeverSink(): $CancellablePromise<filter$0.ExoticEntry[] | null> {
    return $Call.ByID(2966069900);
}

/**
 * ExplainItem tells which rule of the written filter decides the item in
 * the copied text (Alt+E's), and whether that is certain.
 */
export function ExplainItem(raw: string): $CancellablePromise<$models.FilterExplanation> {
    return $Call.ByID(3149791955, raw);
}

/**
 * ExportFilter saves a copy of the filter that was last written, for sharing or
 * for using it on a machine that does not run this app.
 */
export function ExportFilter(): $CancellablePromise<string> {
    return $Call.ByID(1852886141);
}

/**
 * ExportProfile writes a profile to a file another player can import.
 */
export function ExportProfile(name: string): $CancellablePromise<string> {
    return $Call.ByID(1520493660, name);
}

/**
 * ExportScan asks where to put the scan results and writes them there. It
 * returns the chosen path, or an empty string when the user cancels.
 */
export function ExportScan(): $CancellablePromise<string> {
    return $Call.ByID(3249742962);
}

/**
 * FetchOverlayListings loads the next page of a search the overlay already
 * ran. It uses fetch quota only, so the result list can grow as it scrolls.
 */
export function FetchOverlayListings(searchID: string, ids: string[] | null): $CancellablePromise<trade$0.EvaluatedListing[] | null> {
    return $Call.ByID(3150189984, searchID, ids);
}

/**
 * FitOverlay sets the compact overlay's height to the page's content (in page
 * pixels). A worth card or the hide panel fits within the normal height; a
 * search never gets shorter than it, only taller. The window keeps its top
 * edge unless it would run past the game's bottom.
 */
export function FitOverlay(height: number): $CancellablePromise<void> {
    return $Call.ByID(1569686900, height);
}

/**
 * FollowProfile downloads a published profile, adds it as a followed
 * profile and switches to it.
 */
export function FollowProfile(id: string): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(3014892149, id);
}

/**
 * GetAppUpdateState returns the cached application-update status without doing
 * network work, so opening the settings panel stays instant.
 */
export function GetAppUpdateState(): $CancellablePromise<appupdate$0.State> {
    return $Call.ByID(1207992012);
}

/**
 * GetConfig returns the current settings.
 */
export function GetConfig(): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(1258871413);
}

export function GetCraftPrices(): $CancellablePromise<$models.CraftPrices> {
    return $Call.ByID(673939037);
}

/**
 * GetExpeditionView returns the labels last read, for a window that opens
 * after the read.
 */
export function GetExpeditionView(): $CancellablePromise<$models.ExpeditionView> {
    return $Call.ByID(325550741);
}

export function GetMarketSnapshot(): $CancellablePromise<overlay$0.Snapshot> {
    return $Call.ByID(202049859);
}

/**
 * GetMeta returns static app information.
 */
export function GetMeta(): $CancellablePromise<$models.Meta> {
    return $Call.ByID(4134938394);
}

export function GetOverlayDraft(): $CancellablePromise<trade$0.EvaluateRequest> {
    return $Call.ByID(1871640596);
}

export function GetOverlaySettings(): $CancellablePromise<overlay$0.Settings> {
    return $Call.ByID(1767040864);
}

export function GetOverlaySnapshot(): $CancellablePromise<overlay$0.Snapshot> {
    return $Call.ByID(1981238389);
}

export function GetSavedOverlaySearches(): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(2874335354);
}

export function GetStartupStatus(): $CancellablePromise<$models.StartupStatus> {
    return $Call.ByID(2276490042);
}

/**
 * GetState returns the current engine state.
 */
export function GetState(): $CancellablePromise<engine$0.State> {
    return $Call.ByID(987518488);
}

export function GetTradeCatalog(): $CancellablePromise<overlay$0.Catalog> {
    return $Call.ByID(2776211382);
}

export function GetUIThemes(): $CancellablePromise<uitheme$0.State> {
    return $Call.ByID(2536073259);
}

export function HideCraft(): $CancellablePromise<void> {
    return $Call.ByID(542188985);
}

/**
 * HideItem adds an entry to the "hidden by me" list (Alt+H) and rewrites the
 * filter. An entry with the same base and limits is replaced.
 */
export function HideItem(entry: filter$0.HiddenItem): $CancellablePromise<$models.HideResult> {
    return $Call.ByID(3565255278, entry);
}

export function HideMarket(): $CancellablePromise<void> {
    return $Call.ByID(1478215353);
}

export function HideOverlay(): $CancellablePromise<void> {
    return $Call.ByID(3763686891);
}

/**
 * HidePanel hides the tray panel.
 */
export function HidePanel(): $CancellablePromise<void> {
    return $Call.ByID(755575069);
}

/**
 * ImportProfile adds a profile from a file and switches to it. An empty name
 * means the user cancelled the dialog.
 */
export function ImportProfile(): $CancellablePromise<string> {
    return $Call.ByID(2796992417);
}

/**
 * ImportScan asks for a file exported by another player and merges it. A nil
 * result means the user cancelled the dialog.
 */
export function ImportScan(): $CancellablePromise<trade$0.ImportResult | null> {
    return $Call.ByID(1818670661);
}

/**
 * InstallAppUpdate starts the staged updater and exits this process. The
 * updater waits until Windows releases this executable before replacing it.
 */
export function InstallAppUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3880796138);
}

/**
 * Languages lists the interface languages, each named in its own language.
 * The first entry follows the Windows display language.
 */
export function Languages(): $CancellablePromise<$models.LanguageOption[] | null> {
    return $Call.ByID(1608746360);
}

/**
 * Leagues lists the leagues for the picker, live list first, always including
 * the one currently configured.
 */
export function Leagues(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2111230457);
}

/**
 * ListSounds returns the sound files in the PoE2 filter folder, which is where
 * the game looks for CustomAlertSound files.
 */
export function ListSounds(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3747684497);
}

/**
 * LiveResults are a live search's found listings, newest first.
 */
export function LiveResults(id: string): $CancellablePromise<trade$0.EvaluatedListing[] | null> {
    return $Call.ByID(3726817503, id);
}

/**
 * LiveSearches lists the live searches started in this session.
 */
export function LiveSearches(): $CancellablePromise<trade$0.LiveState[] | null> {
    return $Call.ByID(1469155687);
}

/**
 * MoveOverlaySearch puts a saved search into a folder ("" = top level).
 */
export function MoveOverlaySearch(id: string, folder: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(389826432, id, folder);
}

/**
 * NeverSinkThemes lists NeverSink's named styles from the current base filter.
 */
export function NeverSinkThemes(): $CancellablePromise<filter$0.Theme[] | null> {
    return $Call.ByID(653953260);
}

/**
 * OpenAppUpdatePage opens the trusted GitHub release page in the default
 * browser. Only URLs originating from the fixed GitHub API are accepted.
 */
export function OpenAppUpdatePage(): $CancellablePromise<void> {
    return $Call.ByID(2618702970);
}

/**
 * OpenBrowserExtensionFolder writes the extension out and shows its folder,
 * which is what "Load unpacked" asks for.
 */
export function OpenBrowserExtensionFolder(): $CancellablePromise<string> {
    return $Call.ByID(3305854032);
}

/**
 * OpenCommunityLink opens one of the fixed community addresses in the default
 * browser. The frontend only names the button; it never supplies a URL.
 */
export function OpenCommunityLink(kind: string): $CancellablePromise<void> {
    return $Call.ByID(1224008018, kind);
}

/**
 * OpenDataFolder opens the app's data folder in Explorer.
 */
export function OpenDataFolder(): $CancellablePromise<void> {
    return $Call.ByID(1159571193);
}

/**
 * OpenExtensionsPage opens a browser on its extensions page. A browser only
 * opens its internal pages when started with one, not through a link.
 */
export function OpenExtensionsPage(id: string): $CancellablePromise<void> {
    return $Call.ByID(1268585860, id);
}

/**
 * OpenGameFolder opens the PoE2 filter folder in Explorer.
 */
export function OpenGameFolder(): $CancellablePromise<void> {
    return $Call.ByID(3230654855);
}

/**
 * OpenLinkIn opens the pending connection link in a chosen browser, started
 * directly with the link: the extension may live in a browser other than
 * Windows' default, and opening through the default handler failed silently.
 */
export function OpenLinkIn(id: string): $CancellablePromise<void> {
    return $Call.ByID(3314316502, id);
}

export function OpenStartupSettings(): $CancellablePromise<void> {
    return $Call.ByID(2641595979);
}

export function OpenTradePage(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(3122437006, rawURL);
}

/**
 * OverlayQuota reports how full GGG's search windows are for this IP, so the
 * overlay can show who is spending the quota and why a search waits.
 */
export function OverlayQuota(): $CancellablePromise<trade$0.QuotaStatus> {
    return $Call.ByID(1134275129);
}

/**
 * ParseCraftText parses a synthetic item without replacing the captured item.
 */
export function ParseCraftText(raw: string): $CancellablePromise<overlay$0.Snapshot> {
    return $Call.ByID(1559016661, raw);
}

/**
 * ParseOverlayText is also useful for diagnostics: a copied item can be pasted
 * into the expanded market without needing to synthesize game input.
 */
export function ParseOverlayText(raw: string): $CancellablePromise<overlay$0.Snapshot> {
    return $Call.ByID(4205673987, raw);
}

/**
 * PrepareBrowserExtension writes the extension into the data folder, where
 * the browser can load it ("Load unpacked"), and returns that folder.
 */
export function PrepareBrowserExtension(): $CancellablePromise<string> {
    return $Call.ByID(1427588265);
}

/**
 * PreviewGameSound plays one of the game's own alert sounds. The sound ships
 * with the app and is written out on first use, since playback needs a path.
 */
export function PreviewGameSound(id: string, volume: number): $CancellablePromise<void> {
    return $Call.ByID(3813226844, id, volume);
}

/**
 * PreviewOverlay opens the compact window without touching the clipboard. It
 * lets users verify placement and scale from Settings; the latest item remains
 * visible when one has already been captured.
 */
export function PreviewOverlay(): $CancellablePromise<void> {
    return $Call.ByID(3569325213);
}

/**
 * PreviewSound plays a sound file from the filter folder at a filter volume
 * (0 for the loudest).
 */
export function PreviewSound(name: string, volume: number): $CancellablePromise<void> {
    return $Call.ByID(4082593774, name, volume);
}

/**
 * ProfilePublishInfo describes a profile for the publish form.
 */
export function ProfilePublishInfo(name: string): $CancellablePromise<$models.PublishInfo> {
    return $Call.ByID(3775769357, name);
}

/**
 * Profiles lists the saved settings sets for the picker.
 */
export function Profiles(): $CancellablePromise<engine$0.ProfileInfo[] | null> {
    return $Call.ByID(1685047943);
}

/**
 * PublicProfileReasons are the reasons a report may give.
 */
export function PublicProfileReasons(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3372140574);
}

/**
 * PublicProfileTags are the labels an author may choose from.
 */
export function PublicProfileTags(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2324903904);
}

/**
 * PublicProfiles lists one page of published profiles (most followed first),
 * optionally searched by name/author and narrowed to a tag.
 */
export function PublicProfiles(query: string, tag: string, page: number): $CancellablePromise<publicprofile$0.Listing[] | null> {
    return $Call.ByID(221097826, query, tag, page);
}

/**
 * PublishProfile publishes a profile, or updates the published copy. Only
 * the filter settings go; sound files fall back to built-in sounds.
 */
export function PublishProfile(name: string, meta: publicprofile$0.Meta): $CancellablePromise<publicprofile$0.Listing> {
    return $Call.ByID(4062430093, name, meta);
}

/**
 * Quit exits the application.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2015085462);
}

/**
 * QuoteCurrency prices a stackable item from the filter's price snapshot.
 */
export function QuoteCurrency(name: string): $CancellablePromise<overlay$0.CurrencyQuote> {
    return $Call.ByID(978223596, name);
}

export function RefreshTradeCatalog(): $CancellablePromise<overlay$0.Catalog> {
    return $Call.ByID(2146022305);
}

/**
 * RenameProfile changes a saved profile's name without duplicating it.
 */
export function RenameProfile(oldName: string, newName: string): $CancellablePromise<engine$0.ProfileInfo[] | null> {
    return $Call.ByID(2943551420, oldName, newName);
}

export function RenameSearchFolder(id: string, name: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(1207155631, id, name);
}

/**
 * ReportProfile flags a published profile for moderation.
 */
export function ReportProfile(id: string, reason: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(1581234324, id, reason, note);
}

/**
 * SaveConfig stores new settings and returns them normalised.
 */
export function SaveConfig(c: filter$0.Config): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(3644300550, c);
}

/**
 * SaveCraftLibrary replaces the saved crafts with data, a JSON array.
 */
export function SaveCraftLibrary(data: string): $CancellablePromise<void> {
    return $Call.ByID(348271293, data);
}

export function SaveOverlaySearch(name: string, folder: string, query: trade$0.EvaluateRequest): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(433513828, name, folder, query);
}

export function SaveOverlaySettings(next: overlay$0.Settings): $CancellablePromise<overlay$0.Settings> {
    return $Call.ByID(3139009605, next);
}

/**
 * SaveProfileAs stores the current settings under a name and makes it active.
 */
export function SaveProfileAs(name: string): $CancellablePromise<engine$0.ProfileInfo[] | null> {
    return $Call.ByID(3751431605, name);
}

export function SaveUITheme(theme: uitheme$0.Theme): $CancellablePromise<uitheme$0.State> {
    return $Call.ByID(1693342699, theme);
}

/**
 * SearchItems finds uniques, currency and bases for the custom lists.
 */
export function SearchItems(query: string): $CancellablePromise<insights$0.SearchItem[] | null> {
    return $Call.ByID(343239747, query);
}

export function SelectUITheme(id: string): $CancellablePromise<uitheme$0.State> {
    return $Call.ByID(3676360300, id);
}

/**
 * Recording temporarily releases our registrations so Windows delivers even
 * the existing combination to the focused input. Blur restores them.
 */
export function SetHotkeyCapture(active: boolean): $CancellablePromise<void> {
    return $Call.ByID(389946909, active);
}

/**
 * SetLiveAlerts changes how a live search announces a find, without touching
 * the overlay's shortcuts.
 */
export function SetLiveAlerts(sound: string, notify: boolean): $CancellablePromise<overlay$0.Settings> {
    return $Call.ByID(2418144930, sound, notify);
}

export function SetStartupEnabled(enabled: boolean): $CancellablePromise<$models.StartupStatus> {
    return $Call.ByID(1350568245, enabled);
}

export function ShowCraft(): $CancellablePromise<void> {
    return $Call.ByID(2383005206);
}

/**
 * ShowCraftFromOverlay opens the craft window with the item last copied for
 * the price check, so its affixes can be tried further.
 */
export function ShowCraftFromOverlay(): $CancellablePromise<void> {
    return $Call.ByID(3038989938);
}

export function ShowCraftMarketWithQuery(raw: string, $in: trade$0.EvaluateRequest): $CancellablePromise<void> {
    return $Call.ByID(3970537054, raw, $in);
}

export function ShowMarket(): $CancellablePromise<void> {
    return $Call.ByID(760829100);
}

export function ShowMarketWithQuery($in: trade$0.EvaluateRequest): $CancellablePromise<void> {
    return $Call.ByID(4123062592, $in);
}

/**
 * ShowSettings opens the settings window, on a given section when one is
 * named, and puts the tray panel away: the two are never needed at once.
 */
export function ShowSettings(section: string): $CancellablePromise<void> {
    return $Call.ByID(3765493377, section);
}

/**
 * StartLiveSearch opens a live search for a saved search.
 */
export function StartLiveSearch(id: string): $CancellablePromise<trade$0.LiveState[] | null> {
    return $Call.ByID(1942713993, id);
}

/**
 * StatTiers returns the modifier tier tables of a base, or of an item class
 * when the search names only a category. An empty list means none are known
 * (the tiers could not be built yet, or the item rolls no tiered stats).
 */
export function StatTiers(baseType: string, itemClass: string): $CancellablePromise<overlay$0.TierTable[] | null> {
    return $Call.ByID(1744106300, baseType, itemClass);
}

export function StopLiveSearch(id: string): $CancellablePromise<trade$0.LiveState[] | null> {
    return $Call.ByID(2125919487, id);
}

/**
 * StyleGroups lists the drop groups whose colours can be changed.
 */
export function StyleGroups(): $CancellablePromise<filter$0.StyleGroup[] | null> {
    return $Call.ByID(1282843822);
}

/**
 * StyleOptions lists the colours and minimap shapes allowed in custom styles.
 */
export function StyleOptions(): $CancellablePromise<$models.StyleOptions> {
    return $Call.ByID(1554560376);
}

/**
 * SwitchProfile loads another profile, applies it and rewrites the filter, so
 * changing what you farm is one click rather than a dozen sliders.
 */
export function SwitchProfile(name: string): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(933794530, name);
}

/**
 * Themes lists the selectable colour palettes.
 */
export function Themes(): $CancellablePromise<filter$0.Theme[] | null> {
    return $Call.ByID(2599442291);
}

/**
 * TradeCurrencies lists the currencies listings are priced in, with icons,
 * without sending the whole stat catalog to a window that only shows prices.
 */
export function TradeCurrencies(): $CancellablePromise<overlay$0.CurrencyEntry[] | null> {
    return $Call.ByID(3072648418);
}

/**
 * TravelToHideout takes the player to the seller's hideout for an instant
 * buyout listing (needs the pathofexile.com session and the game running on
 * the same account).
 */
export function TravelToHideout(token: string): $CancellablePromise<void> {
    return $Call.ByID(1913675916, token);
}

/**
 * UIZoom is the CSS zoom a window's page applies to itself (1 = none), for a
 * page that loads after the window was sized.
 */
export function UIZoom(window: string): $CancellablePromise<number> {
    return $Call.ByID(2495769444, window);
}

/**
 * UnhideItem removes the entry with the same base and limits and rewrites
 * the filter.
 */
export function UnhideItem(entry: filter$0.HiddenItem): $CancellablePromise<$models.HideResult> {
    return $Call.ByID(740063393, entry);
}

/**
 * UniqueIcons maps unique names to their art, from the last price snapshot
 * (poe.ninja sends an icon with each unique). An unidentified unique shows
 * these so the player can tell the candidates apart by their look.
 */
export function UniqueIcons(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1751108448);
}

/**
 * UnpublishProfile removes a profile from the server; followers keep their
 * last copy.
 */
export function UnpublishProfile(name: string): $CancellablePromise<void> {
    return $Call.ByID(2496674306, name);
}

/**
 * UpdateNow starts a filter update in the background.
 */
export function UpdateNow(): $CancellablePromise<void> {
    return $Call.ByID(1730923500);
}

/**
 * UserGroupTemplate is the look and sound a new user group starts from, so the
 * panel can render its colour picker like the built-in groups.
 */
export function UserGroupTemplate(): $CancellablePromise<filter$0.StyleGroup> {
    return $Call.ByID(1561983083);
}
