// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CurrencyPrice is a stackable/bulk item (currency, runes, omens, essences...).
 */
export interface CurrencyPrice {
    "name": string;
    "api_id"?: string;
    "category": string;
    "value_ex": number;
}
