// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Action is what a block does to the items it matches.
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Show = "Show",
    Hide = "Hide",
    Minimal = "Minimal",
};

/**
 * Block is one Show/Hide/Minimal rule of the filter.
 */
export interface Block {
    "action": Action;
    "continue": boolean;
    "conds": Cond[] | null;

    /**
     * Line is the 1-based line of the block's first line in the file.
     */
    "line": number;
    "source": Source;

    /**
     * Section is the nearest heading above the block: our section title or
     * NeverSink's waypoint title ("Jewellery - Endgame Magic&Normal").
     */
    "section": string;

    /**
     * Type and Tier are NeverSink's "$type->..." and "$tier->..." tags,
     * Style its "!style" tag; empty for our rules.
     */
    "type"?: string;
    "tier"?: string;
    "style"?: string;

    /**
     * Text is the block as written, conditions and looks.
     */
    "text": string;
}

/**
 * Cond is one condition line: Key, an optional operator and its values
 * ("Rarity Normal Magic", "ItemLevel >= 82", `HasExplicitMod >=1 "Merciless"`).
 */
export interface Cond {
    "key": string;
    "op": string;
    "values": string[] | null;

    /**
     * Count is HasExplicitMod's own comparison ("HasExplicitMod >=2 ...");
     * CountOp is empty when the line gives none (at least one).
     */
    "countOp"?: string;
    "count"?: number;
    "line": string;
}

/**
 * Match is a block that matched the item, surely or maybe.
 */
export interface Match {
    "block": Block;

    /**
     * Unknown lists the conditions the item text could not decide; empty
     * for a certain match.
     */
    "unknown"?: string[] | null;
}

/**
 * Source tells whose rule a block is.
 */
export enum Source {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * our generated block ([[DYNAMIC LOOT FILTER]])
     */
    SourceOurs = "ours",

    /**
     * the base filter
     */
    SourceNeverSink = "neversink",
};

/**
 * Verdict is the item's fate in a few words.
 */
export enum Verdict {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VerdictShow = "show",
    VerdictHide = "hide",
    VerdictMinimal = "minimal",

    /**
     * no rule matches: the game shows it plainly
     */
    VerdictNone = "none",
};
