// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Listing is a published profile as the server lists it.
 */
export interface Listing {
    "id": string;
    "author": string;
    "name": string;
    "description": string;
    "tags": string[] | null;
    "version": number;
    "followers": number;
    "updated_at": number;
    "hidden"?: boolean;
}

/**
 * Meta describes a published profile in the listing.
 */
export interface Meta {
    "name": string;
    "description": string;
    "tags": string[] | null;
}

/**
 * SoundSwap is a style group whose own sound file was left out of the shared
 * profile; followers hear the group's built-in sound instead.
 */
export interface SoundSwap {
    /**
     * style group key, as in filter.Config.Sounds
     */
    "group": string;

    /**
     * the file name the author uses
     */
    "file": string;
}
