// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trade$0 from "../trade/models.js";

/**
 * Catalog is the normalized data the two overlay windows consume. The raw
 * endpoint responses remain on disk so new GGG fields are not destroyed.
 */
export interface Catalog {
    "stats": StatGroup[] | null;
    "items": ItemGroup[] | null;
    "filters": FilterGroup[] | null;

    /**
     * Currencies are the trade site's exchange items by the id listings price
     * in ("divine", "exalted"), with their name and icon.
     */
    "currencies": CurrencyEntry[] | null;
    "updatedAtMs": number;
}

/**
 * ChatCommand is a shortcut and the chat line it sends. In Text, {last}
 * stands for the player who whispered last.
 */
export interface ChatCommand {
    "hotkey": string;
    "text": string;
}

export interface CurrencyEntry {
    "id": string;
    "text": string;
    "image": string;

    /**
     * Group is the exchange section ("Currency", "Ritual", "Waystones"...).
     */
    "group": string;
}

/**
 * CurrencyQuote is what the overlay shows for a stackable item: its value in
 * the price snapshot the filter already uses, so no trade search is needed.
 */
export interface CurrencyQuote {
    "found": boolean;
    "name": string;
    "category": string;
    "valueEx": number;
    "divineEx": number;
    "chaosEx": number;
    "league": string;
    "generatedAt": string;
}

export interface FilterGroup {
    "id": string;
    "title": string;
    "filters": TradeFilter[] | null;
}

export interface FilterInput {
    "placeholder": string;
}

export interface Item {
    "raw": string;
    "class": string;
    "rarity": string;
    "name": string;
    "baseType": string;
    "itemLevel": number;
    "requiredLevel": number;
    "quality": number;

    /**
     * RuneSockets counts the "S" entries of the Sockets line.
     */
    "runeSockets": number;

    /**
     * A gem's level and support sockets ("Sockets: G G"); zero on other items.
     */
    "gemLevel": number;
    "gemSockets": number;

    /**
     * GemCorruption is the part of GemLevel a corruption added ("+1").
     */
    "gemCorruption": number;

    /**
     * Exceptional is set when the game prefixed the name with "Exceptional":
     * extra sockets or quality are then what the item is priced by.
     */
    "exceptional": boolean;

    /**
     * StackSize is the count of a stackable item ("Stack Size: 808/5000").
     */
    "stackSize": number;
    "unidentified": boolean;
    "fractured": boolean;
    "corrupted": boolean;

    /**
     * TwiceCorrupted is its own state: a corrupted item corrupted again with
     * another item. It is not also reported as Corrupted.
     */
    "twiceCorrupted": boolean;
    "sanctified": boolean;
    "mirrored": boolean;
    "properties": ItemProperty[] | null;
    "mods": ItemMod[] | null;

    /**
     * Exchange is the currency exchange id of an item that trades only there
     * (see exchangeID); such items get a worth card and no search.
     */
    "exchange"?: string;
}

export interface ItemEntry {
    "type": string;
    "text"?: string;
    "name"?: string;
}

export interface ItemGroup {
    "id": string;
    "label": string;
    "entries": ItemEntry[] | null;
}

export interface ItemMod {
    "key": string;
    "statId": string;
    "text": string;
    "type": string;
    "affix": string;
    "name": string;
    "tier": number;
    "values": number[] | null;
    "selected": boolean;

    /**
     * Tiers lists each affix's tier when several affixes of the same stat
     * were merged into this line ("P1+P1"); empty for a single affix.
     */
    "tiers"?: number[] | null;

    /**
     * Affixes lists each merged affix's side ("prefix", "suffix") in the
     * order of Tiers, so the panel can write "P1+S1".
     */
    "affixes"?: string[] | null;

    /**
     * AltStatIDs are catalog stats with the same wording as StatID (a local
     * or global twin); searches accept any of them through a count group.
     */
    "altStatIds"?: string[] | null;

    /**
     * Negated marks a "reduced" line searched as the site's "increased" stat
     * (or the other way round): Values are negated, and a search keeps the
     * value as the maximum ("at most -29% increased" = "at least 29% reduced").
     */
    "negated"?: boolean;

    /**
     * WeightStats makes the line a sum the trade site adds up itself: it is
     * searched as a Weighted Sum v2 group of these stats, weight 1 each, with
     * the line's value as the group's minimum. StatID is then only a key.
     */
    "weightStats"?: string[] | null;

    /**
     * Hidden lines start unselected under a closed "hidden lines" section:
     * the ones a total stands in for, and totals another one makes redundant.
     */
    "hidden"?: boolean;
}

export interface ItemProperty {
    "name": string;
    "value": string;
}

export interface SavedSearch {
    "id": string;
    "name": string;

    /**
     * folder id, "" at the top level
     */
    "folder"?: string;
    "query": trade$0.EvaluateRequest;
    "createdAt": string;
}

export interface SearchFolder {
    "id": string;
    "name": string;
}

/**
 * SearchLibrary is everything the market's saved list shows: the folders in
 * the user's order and the searches, each naming its folder.
 */
export interface SearchLibrary {
    "folders": SearchFolder[] | null;
    "searches": SavedSearch[] | null;
}

export interface SelectOption {
    "id": string;
    "text": string;
}

/**
 * Settings are stored in overlay.json next to config.json.
 */
export interface Settings {
    "enabled": boolean;
    "hotkey": string;

    /**
     * MarketHotkey opens the full market window with a fresh search.
     */
    "market_hotkey": string;
    "craft_hotkey": string;

    /**
     * HideHotkey reads the item under the cursor and offers to add it to the
     * loot filter's "hidden by me" list.
     */
    "hide_hotkey": string;

    /**
     * ChatEnabled turns on Commands: shortcuts that type a line into the
     * game's chat. Like the overlay it sends keys to the game, so it starts
     * off. The keys are taken only while the game is the active window, so
     * they keep working everywhere else (F5 still reloads a browser page).
     */
    "chat_enabled": boolean;
    "chat_commands": ChatCommand[] | null;

    /**
     * PanelHotkey opens the main panel, as a click on the tray icon does.
     * Like the commands it is taken only while the game is the active window.
     */
    "panel_hotkey": string;

    /**
     * HideoutHotkey and DndHotkey were the first two fixed commands; an
     * overlay.json that has them gets them as its first two Commands.
     */
    "hideout_hotkey"?: string;
    "dnd_hotkey"?: string;
    "auto_scale": boolean;
    "ui_scale": number;

    /**
     * LiveSound is the game alert sound played when a live search finds a
     * listing ("none" = silent); LiveNotify shows a Windows notification.
     */
    "live_sound": string;
    "live_notify": boolean;
}

/**
 * Snapshot is kept by the service so windows opened after the hotkey event can
 * still render the latest item (or the capture error that explains why not).
 */
export interface Snapshot {
    "item"?: Item | null;
    "error"?: string;

    /**
     * Mode is "hide" when the item was read with the hide shortcut (Alt+H):
     * the window then offers to hide it instead of pricing it.
     */
    "mode"?: string;
}

export interface StatEntry {
    "id": string;
    "text": string;
    "type": string;
}

export interface StatGroup {
    "id": string;
    "label": string;
    "entries": StatEntry[] | null;
}

/**
 * Tier is one tier of a modifier family: T1 is the best, the one needing the
 * highest item level. Min and Max are what the trade site compares ("Adds X to
 * Y" by the average of the two).
 */
export interface Tier {
    "tier": number;
    "name": string;
    "level": number;
    "min": number;
    "max": number;
}

/**
 * TierTable is the tiers of one stat line of one modifier family on a base.
 * A hybrid family rolls another stat too (With names it); its tiers are
 * smaller than the plain family's, so the two are offered apart. A line
 * without a value ("Upgrades Radius to Large") has no tiers: the table only
 * says that the base rolls it.
 */
export interface TierTable {
    "stat": string;
    "affix": string;
    "hybrid": boolean;
    "with"?: string;
    "tiers": Tier[] | null;
}

export interface TradeFilter {
    "id": string;
    "text": string;
    "minMax": boolean;
    "option": optionList;

    /**
     * Input is set for free-text filters (the seller account name).
     */
    "input"?: FilterInput | null;
}

export interface optionList {
    "options": SelectOption[] | null;
}
