// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartupStatus describes the startup controls Windows permits for this app.
 */
export interface StartupStatus {
    "enabled": boolean;
    "canChange": boolean;
    "state": string;
}
